# Generated by Django 2.1.3 on 2018-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('empname', models.CharField(max_length=30)),
                ('empsal', models.FloatField()),
                ('empadd', models.CharField(max_length=30)),
            ],
        ),
    ]
